/* #include QMK_KEYBOARD_H

enum layer_names {
    _NP,
    _BL
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_NP] = LAYOUT_ortho_6x4(
        KC_ESC,  KC_TAB,  KC_BSPC, MO(_BL),
        KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
        KC_P7,   KC_P8,   KC_P9,   KC_PPLS,
        KC_P4,   KC_P5,   KC_P6,   KC_PPLS,
        KC_P1,   KC_P2,   KC_P3,   KC_PENT,
        KC_P0,   KC_DOT,  KC_PDOT, KC_PENT
    ),

    [_BL] = LAYOUT_ortho_6x4(
        _______, _______, _______, _______,
        _______, _______, _______, _______,
        _______, BL_ON,   _______, BL_INC,
        _______, BL_TOGG, _______, BL_INC,
        _______, BL_OFF,  _______, BL_DEC,
        BL_BRTG, _______, _______, BL_DEC
    )
}; */
#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 *
 *
 *
 */

enum unicode_names {
    SMILEY,
    SWEAT,
    HALO,
    THINKS,
    SICK,
    SAD,
    FEAR,
    ANGRY,
    PIRATE,
    POO,
    CLOWN,
    CAT,
    SENE,
    HNE,
    SPNE,
    HUNDRED,
    POW,
    BOMB,
    WAVE,
    THUMBUP,
    CLAP,
    FACEPALM,
    SUPERH,
    UNICORN,
    MUSHRM,
    BURGR,
    COOKIE,
    BDAY,
    COFFEE,
    BEER,
    HOUSE,
    CAR,
    TROPHY,
    PHONE,
    GUN
};

const uint32_t PROGMEM unicode_map[] = {
    [SMILEY] = 	0x1F600,
    [SWEAT] =  0x1F605,
    [HALO] = 	0x1F607,
    [THINKS] = 0x1F914,
    [SICK] = 0x1F922,
    [SAD] = 0x1F641,
    [FEAR] = 0x1F631,
    [ANGRY] = 0x1F620,
    [PIRATE] =	0x2620,
    [POO]	= 0x1F4A9,
    [CLOWN] = 	0x1F921,
    [CAT] = 0x1F63A,
    [SENE] =	0x1F648,
    [HNE] = 0x1F649,
    [SPNE] = 0x1F64A,
    [HUNDRED] = 0x1F4AF,
    [POW] = 0x1F4A5,
    [BOMB] = 0x1F4A3,
    [WAVE] = 0x1F44B,
    [THUMBUP] = 	0x1F44D,
    [CLAP] = 0x1F44F,
    [FACEPALM] = 0x1F926,
    [SUPERH] = 0x1F9B8,
    [UNICORN] = 0x1F984,
    [MUSHRM] = 0x1F344,
    [BURGR] = 0x1F354,
    [COOKIE] = 0x1F36A,
    [BDAY] = 0x1F382,
    [COFFEE] = 0x2615,
    [BEER] = 0x1F37A,
    [HOUSE] = 0x1F3E1,
    [CAR] = 0x1F697,
    [TROPHY] = 0x1F3C6,
    [PHONE] = 0x260E,
    [GUN] = 0x1F52B,
};

enum layer_names {
    _0,
    _1,
    _2
};

/* const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_6x4(RGB_TOG, BL_TOGG, TG(2), TG(1),
                           KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
                           KC_P7, KC_P8, KC_P9, KC_PPLS,
                           KC_P4, KC_P5, KC_P6, KC_PPLS,
                           KC_P1, KC_P2, KC_P3, KC_PENT,
                           KC_P0, KC_DOT, KC_PDOT, KC_PENT),
	[1] = LAYOUT_ortho_6x4(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                           RGB_MOD, RGB_HUI, RGB_SAI, RGB_SPI,
                           RGB_RMOD, RGB_HUD, RGB_SAD, RGB_SPD,
                           KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                           KC_TRNS, KC_TRNS, KC_TRNS, BL_INC,
                           BL_BRTG, BL_ON, BL_OFF, BL_DEC),
	[2] = LAYOUT_ortho_6x4(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                           KC_MSTP, KC_VOLU, KC_VOLD, KC_MUTE,
                           KC_NO, KC_NO, KC_NO, KC_NO, KC_F13,
                           KC_F14, KC_F15, KC_F16, KC_F17,
                           KC_F18, KC_F19, KC_F20, KC_F21,
                           KC_F22, KC_F23, KC_F24)
}; */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_6x4(TO(0), TO(1), TO(2), TO(3),
                           KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS,
                           KC_P7, KC_P8, KC_P9, KC_PPLS,
                           KC_P4, KC_P5, KC_P6, KC_PPLS,
                           KC_P1, KC_P2, KC_P3, KC_PENT,
                           KC_P0, KC_DOT, KC_PDOT, KC_PENT),
	[1] = LAYOUT_ortho_6x4(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                           XP(SMILEY, SAD), X(SAD), X(HALO), X(SWEAT),
                           X(THINKS), X(SICK), X(FEAR), X(ANGRY),
                           X(PIRATE), X(POO), X(CLOWN), X(CAT),
                           X(POW), X(BOMB), X(WAVE), X(THUMBUP),
                           X(CLAP), X(FACEPALM), X(SUPERH), X(UNICORN)),
	[2] = LAYOUT_ortho_6x4(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                           X(MUSHRM), X(BURGR), X(GUN), X(BEER),
                           X(HOUSE),  X(CAR), X(COFFEE), X(TROPHY),
                           KC_F13, KC_F14, KC_F15, KC_F16,
                           KC_F17, KC_F18, KC_F19, KC_F20,
                           KC_F21, KC_F22, KC_F23, KC_F24),
    [3] = LAYOUT_ortho_6x4(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                           KC_NO, KC_NO, KC_NO, KC_NO,
                           KC_NO, KC_NO, KC_NO, KC_NO,
                           KC_NO, KC_NO, KC_NO, KC_NO,
                           BL_TOGG, BL_STEP, KC_NO, BL_INC,
                           BL_BRTG, BL_ON, BL_OFF, BL_DEC),
};


/* const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_0] = LAYOUT_ortho_6x4(BL_TOGG, TO(0), TG(2), TG(1),
                            KC_NUMLOCK, KC_KP_SLASH, KC_KP_ASTERISK, KC_KP_MINUS,
        ls /dev/sh                      KC_KP_7, KC_KP_8, KC_KP_9, KC_KP_PLUS,
                            KC_KP_4, KC_KP_5, KC_KP_6 KC_KP_PLUS,
                            KC_KP_1, KC_KP_2, KC_KP_3, KC_PENT,
                            KC_KP_0, KC_KP_DOT, KC_KP_DOT, KC_KP_ENTER),
	[_1] = LAYOUT_ortho_6x4(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                            KC_MPLY, KC_MSTP, KC_MUTE, KC_VOLD,
                            KC_CUT, KC_COPY, KC_PSTE, KC_VOLU,
                            KC_F13, KC_F14, KC_F15, KC_F16,
                            KC_F17, KC_F18, KC_F19, KC_F20,
                            KC_F21, KC_F22, KC_F23, KC_F24),
	[_2] = LAYOUT_ortho_6x4(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
                            BL_STEP, BL_BRTG, BL_OFF, BL_DEC,
                            RGB_TOG, KC_NO, BL_ON, BL_INC,
                            RGB_RMOD, RGB_HUD, RGB_SAD, RGB_VAD,
                            RGB_MOD, RGB_HUI, RGB_SAI, RGB_VAI,
                            KC_NO, KC_NO, KC_NO, KC_NO)
};
 */
